/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTreinoRouteImport } from './routes/_authenticated/app.treino'
import { Route as AuthenticatedAppNutricionalRouteImport } from './routes/_authenticated/app.nutricional'
import { Route as AuthenticatedAppGaleriaRouteImport } from './routes/_authenticated/app.galeria'
import { Route as AuthenticatedAppAdminAlunosRouteImport } from './routes/_authenticated/app.admin.alunos'
import { Route as AuthenticatedAppAdminAlunosNovoRouteImport } from './routes/_authenticated/app.admin.alunos.novo'
import { Route as AuthenticatedAppAdminAlunosIdRouteImport } from './routes/_authenticated/app.admin.alunos.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTreinoRoute = AuthenticatedAppTreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNutricionalRoute =
  AuthenticatedAppNutricionalRouteImport.update({
    id: '/nutricional',
    path: '/nutricional',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGaleriaRoute = AuthenticatedAppGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminAlunosRoute =
  AuthenticatedAppAdminAlunosRouteImport.update({
    id: '/admin/alunos',
    path: '/admin/alunos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminAlunosNovoRoute =
  AuthenticatedAppAdminAlunosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedAppAdminAlunosRoute,
  } as any)
const AuthenticatedAppAdminAlunosIdRoute =
  AuthenticatedAppAdminAlunosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppAdminAlunosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/galeria': typeof AuthenticatedAppGaleriaRoute
  '/app/nutricional': typeof AuthenticatedAppNutricionalRoute
  '/app/treino': typeof AuthenticatedAppTreinoRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/alunos': typeof AuthenticatedAppAdminAlunosRouteWithChildren
  '/app/admin/alunos/$id': typeof AuthenticatedAppAdminAlunosIdRoute
  '/app/admin/alunos/novo': typeof AuthenticatedAppAdminAlunosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/galeria': typeof AuthenticatedAppGaleriaRoute
  '/app/nutricional': typeof AuthenticatedAppNutricionalRoute
  '/app/treino': typeof AuthenticatedAppTreinoRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/alunos': typeof AuthenticatedAppAdminAlunosRouteWithChildren
  '/app/admin/alunos/$id': typeof AuthenticatedAppAdminAlunosIdRoute
  '/app/admin/alunos/novo': typeof AuthenticatedAppAdminAlunosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/galeria': typeof AuthenticatedAppGaleriaRoute
  '/_authenticated/app/nutricional': typeof AuthenticatedAppNutricionalRoute
  '/_authenticated/app/treino': typeof AuthenticatedAppTreinoRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/alunos': typeof AuthenticatedAppAdminAlunosRouteWithChildren
  '/_authenticated/app/admin/alunos/$id': typeof AuthenticatedAppAdminAlunosIdRoute
  '/_authenticated/app/admin/alunos/novo': typeof AuthenticatedAppAdminAlunosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/app/galeria'
    | '/app/nutricional'
    | '/app/treino'
    | '/app/'
    | '/app/admin/alunos'
    | '/app/admin/alunos/$id'
    | '/app/admin/alunos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/galeria'
    | '/app/nutricional'
    | '/app/treino'
    | '/app'
    | '/app/admin/alunos'
    | '/app/admin/alunos/$id'
    | '/app/admin/alunos/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/galeria'
    | '/_authenticated/app/nutricional'
    | '/_authenticated/app/treino'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/alunos'
    | '/_authenticated/app/admin/alunos/$id'
    | '/_authenticated/app/admin/alunos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/treino': {
      id: '/_authenticated/app/treino'
      path: '/treino'
      fullPath: '/app/treino'
      preLoaderRoute: typeof AuthenticatedAppTreinoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/nutricional': {
      id: '/_authenticated/app/nutricional'
      path: '/nutricional'
      fullPath: '/app/nutricional'
      preLoaderRoute: typeof AuthenticatedAppNutricionalRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/galeria': {
      id: '/_authenticated/app/galeria'
      path: '/galeria'
      fullPath: '/app/galeria'
      preLoaderRoute: typeof AuthenticatedAppGaleriaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/alunos': {
      id: '/_authenticated/app/admin/alunos'
      path: '/admin/alunos'
      fullPath: '/app/admin/alunos'
      preLoaderRoute: typeof AuthenticatedAppAdminAlunosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/alunos/novo': {
      id: '/_authenticated/app/admin/alunos/novo'
      path: '/novo'
      fullPath: '/app/admin/alunos/novo'
      preLoaderRoute: typeof AuthenticatedAppAdminAlunosNovoRouteImport
      parentRoute: typeof AuthenticatedAppAdminAlunosRoute
    }
    '/_authenticated/app/admin/alunos/$id': {
      id: '/_authenticated/app/admin/alunos/$id'
      path: '/$id'
      fullPath: '/app/admin/alunos/$id'
      preLoaderRoute: typeof AuthenticatedAppAdminAlunosIdRouteImport
      parentRoute: typeof AuthenticatedAppAdminAlunosRoute
    }
  }
}

interface AuthenticatedAppAdminAlunosRouteChildren {
  AuthenticatedAppAdminAlunosIdRoute: typeof AuthenticatedAppAdminAlunosIdRoute
  AuthenticatedAppAdminAlunosNovoRoute: typeof AuthenticatedAppAdminAlunosNovoRoute
}

const AuthenticatedAppAdminAlunosRouteChildren: AuthenticatedAppAdminAlunosRouteChildren =
  {
    AuthenticatedAppAdminAlunosIdRoute: AuthenticatedAppAdminAlunosIdRoute,
    AuthenticatedAppAdminAlunosNovoRoute: AuthenticatedAppAdminAlunosNovoRoute,
  }

const AuthenticatedAppAdminAlunosRouteWithChildren =
  AuthenticatedAppAdminAlunosRoute._addFileChildren(
    AuthenticatedAppAdminAlunosRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppGaleriaRoute: typeof AuthenticatedAppGaleriaRoute
  AuthenticatedAppNutricionalRoute: typeof AuthenticatedAppNutricionalRoute
  AuthenticatedAppTreinoRoute: typeof AuthenticatedAppTreinoRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAdminAlunosRoute: typeof AuthenticatedAppAdminAlunosRouteWithChildren
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppGaleriaRoute: AuthenticatedAppGaleriaRoute,
  AuthenticatedAppNutricionalRoute: AuthenticatedAppNutricionalRoute,
  AuthenticatedAppTreinoRoute: AuthenticatedAppTreinoRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAdminAlunosRoute:
    AuthenticatedAppAdminAlunosRouteWithChildren,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
